MIP
movementlabsxyz/MIP pull request #15
Opened 2024-09-11 08:25 UTC by l-monninger

# Summary

2024-09-12 09:52 UTC, andyjsbell requested changes
Looks great to me

Looks like you have some commits pulled in here from other branches possibly

2024-09-24 14:29 UTC, apenzk commented
silly question. why is there a MIP15 and a MG15. why not just MIP15?

2024-09-24 14:30 UTC, apenzk commented
what would still be useful is to have a complete document, for ease of overview. Possibly at the root directory. The MG could then come with an addition to a common file (glossary.md) to which the MG contributes. The term introduced in the glossary.md should reference the MD

2024-09-24 14:30 UTC, apenzk commented
I suggest to move the MG template into the MG directory rather than the MIP directory

2024-09-25 14:37 UTC, apenzk commented on MD/md-15/README.md
> +**Justification**: Introducing glossary terms via an MIP will allow for a more formal process for introducing new terms.
```suggestion
**Justification**: Introducing glossary terms via an MIP or MD will allow for a more formal process for introducing new terms.
```

2024-09-25 14:39 UTC, apenzk commented on MD/md-15/README.md
> +**Justification**: Introducing glossary terms via an MIP will allow for a more formal process for introducing new terms.
There is no information at the root README. i have [opened a PR](https://github.com/movementlabsxyz/MIP/pull/22) for this

2024-09-25 14:52 UTC, apenzk requested changes
what would still be useful is to have a complete document, for ease of overview. Possibly at the root directory. The MG could then come with an addition to a common file (glossary.md) to which the MG contributes. The term introduced in the glossary.md should reference the MD.

Edit: i have added PR https://github.com/movementlabsxyz/MIP/pull/22 for this

2024-10-16 13:15 UTC, merged