Mip/security fallliblity
movementlabsxyz/MIP pull request #46
Opened 2024-11-05 17:39 UTC by apenzk

# Summary

2024-11-06 08:01 UTC, 0xmovses requested changes

2024-11-06 08:01 UTC, 0xmovses commented on MIP/mip-security_fallibility/README.md
> +
Expand on this point here, that if an attack were to be carried out on the bridge, we would have a period equal to the initiator timelock to detect it and to stop if from continuing. This slow attack adds an extra layer of resistance to such an attack being truly harmful to the network's users and the token's value.

2024-11-06 11:23 UTC, 0xPrimata requested changes

2024-11-25 11:54 UTC, apenzk commented on MIP/mip-46/README.md
> +
```suggestion
1. Transfer amount has a min and max amount.
```

2024-11-25 11:54 UTC, apenzk commented on MIP/mip-security_fallibility/README.md
> +1. The relayer shall maximize security measurements to protect its keys.
added your suggestion

2025-01-14 10:26 UTC, apenzk commented
As per MIP-committee decision we are closing MIPs and MDs for the HTLC-based Native-bridge.

2025-01-14 10:26 UTC, closed without merging