[review] MIP-57 : Informer for the Operation of the HTLC-based Native Bridge
movementlabsxyz/MIP pull request #57
Opened 2024-11-15 16:33 UTC by apenzk

# Summary

This MIP introduces the Informer as proposed by [the Biarritz Model](https://github.com/movementlabsxyz/MIP/pull/54). 

The informer provides an estimate of the circulating $L1MOVE and $L2MOVE tokens. It acknowledges that the measured value will be off due to 
- inflight tokens 
- differences in the clock of different layers

However it provides some bounds and approaches to get an estimate that should not be too far off. 

[MIP-57](https://github.com/movementlabsxyz/MIP/blob/mip/informer/MIP/mip-57/README.md)

2024-11-15 16:52 UTC, 0xPrimata requested changes

2024-11-15 16:52 UTC, 0xPrimata commented on MIP/mip-57/README.md
> +![L1 to L2 Transfer](L1ToL2.png)
after the user requests funds on target chain, Relayer relays to L1*

2024-12-17 20:58 UTC, franck44 commented
@apenzk The content of the MIP still references the HTLV bridge at some locations. We may replace them with to acknowledge the new architecture?

2024-12-17 20:58 UTC, franck44 commented on MIP/mip-57/README.md
> +The Informer for the HTLC-based Native Bridge (in the following called simply the Native Bridge) is introduced to collect information about the state from L1 and L2 and provide this information to co
HTLC bridge?
Use Native bridge?

2025-01-28 14:17 UTC, apenzk commented
HTLC-based bridge approaches are being closed

2025-01-28 14:17 UTC, closed without merging