[draft] FastConfirmation on L2
movementlabsxyz/MIP pull request #65
Opened 2024-12-09 18:01 UTC by apenzk

# Summary

2025-02-07 22:52 UTC, l-monninger requested changes

2025-02-07 22:52 UTC, l-monninger commented on MD/md-65/README.md
> +**User Journey**: The system is designed to be decentralized.
I would suggest if we produce the certificate off-chain, as under the ZK-FFS MIP (forthcoming), we could avoid some of the complexities here. In theory, both chains could validate without necessarily knowing the other has received under an eventual consistency assumption.

2025-02-07 22:52 UTC, l-monninger commented on MIP/mip-65/README.md
> +
This is obviously missing the proof of whether the Fastconfirmation implementation on the L2 can be included in the state. It's easier to suggest it should not. ZK-FFS also changes this.

2025-02-10 10:25 UTC, apenzk commented on MD/md-65/README.md
> +**User Journey**: The system is designed to be decentralized.
looking forward

2025-02-23 14:35 UTC, apenzk commented on MD/md-65/README.md
> +**User Journey**: The system is designed to be decentralized.
is this comment at the wrong desiderata? it doesnt seem to be related to decentralization but dependency of two chains.

2025-02-23 14:37 UTC, apenzk commented on MIP/mip-65/README.md
> +
> can be included in the state

state of who?

2026-05-18 08:15 UTC, closed without merging